project:
  type: website

website:
  title: "CANDO+P analysis"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mckfarm
format:
  html:
    theme: flatly
    css: styles.css



