---
title: "March 13 2023"
description: |
  In-cycle sampling on Monday, March 13th 2023
categories:
  - in-cycle
author:
  - name: McKenna Farmer
date: 2023-03-13
output:
  distill::distill_article:
    self_contained: false
    code_folding: true
---



```{r function imports, message = FALSE}

source("./scripts/cycle_parsing.R")

```


```{r packages, message = FALSE}
library(MetBrewer)
library(ggplot2)
library(dplyr)
```


```{r import data}
file_path <- "C:/Users/mckyf/Northwestern University/Wells Research Group - CANDO+P Reactor/04 Performance data/cycle_results_2023.xlsx"
choose_date <- "2023-03-13"

df <- cycle_parse(file_path, choose_date)
```



```{r theme defaults - colors and shapes}

theme_defaults <- list(
  theme_classic(),
  theme(legend.position="top", plot.title = element_text(face = "bold")))


```



```{r phase labels and lines}

phase_lines <- list(
  geom_vline(xintercept=1.65,color="grey"),
  geom_vline(xintercept=3.63,color="grey"))

ylim_custom <- 100 # set this after looking at the plot

phase_labs <- list(
  annotate("text", x=0.75, y=ylim_custom, label="anaerobic"),
  annotate("text", x=2.6, y=ylim_custom, label="anoxic"),
  annotate("text", x=4.5, y=ylim_custom, label="aerobic")
)


```


```{r in-cycle plot, warning = FALSE}
plot_list <- c("phosphate", "nitrite", "acetate", "propionate", "glucose")

custom_color <- scale_color_manual(name="Constituent",
                                   values=met.brewer("Hokusai1", 5),
                                   labels=c("Phosphate", "Nitrite",
                                            "Acetate", "Propionate", "Glucose"))

custom_shape <- scale_shape_manual(name="Constituent",
                                   values=c(16, 17, 6, 5, 7),
                                   labels=c("Phosphate", "Nitrite",
                                            "Acetate", "Propionate", "Glucose"))

df %>% filter(variable %in% plot_list) %>%
  ggplot(data=.,aes(x=hour, y=value, color=variable, shape=variable)) +
  geom_point(size=2, alpha=0.8) +
  custom_color +
  custom_shape +
  phase_lines +
  theme_defaults +
  phase_labs +
  labs(y="Concentration\n[mgP/L, mgN/L, mgCOD/L]", x="Hour") +
  ylim(0, ylim_custom)

```

Notes on in-cycle plot:

* Good P release and some anoxic uptake, followed by re-release - should increase NO2 dose
* Rapid COD uptake in anaerobic phase
* Most P uptake is aerobic

